# 测试环境配置
{
  APP: {
    name: "PrivateChatRoomOnlineBackend",
    port: 8099,
    host: "localhost",
  },
  jwt_secret: "PCR_SERVER_SECRET_KEY",
  cors: {
    origin: "*",
    methods: ["GET", "POST", "PUT", "DELETE"],
    allowedHeaders: ["Content-Type", "Authorization"],
    exposedHeaders: ["Content-Type", "Authorization"],
    credentials: true,
    maxAge: 3600,
  },
  rateLimit: {
    windowMs: 15 * 60 * 1000, // 15 minutes
    max: 100, // limit each IP to 100 requests per windowMs
    message: "Too many requests, please try again later.",
    standardHeaders: true, // Return rate limit info in the `RateLimit-*` headers
    legacyHeaders: false, // Disable the `X-RateLimit-*` headers
  },
  database: {
    host: "localhost",
    port: 5432,
    user: "your-username",
    password: "your-password",
    database: "your-dbname",
  },
  redis: {
    host: "localhost",
    port: 6379,
    password: null,
  },
}